# Generated by Django 2.2.1 on 2023-03-12 05:50

from django.db import migrations, models
import django.db.models.deletion
import gifcard.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=gifcard.utils.generate_gifcard, max_length=100, verbose_name='Código Gifcard')),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254, verbose_name='Email Gifcard')),
                ('status', models.BooleanField(default=False, verbose_name='Usada')),
                ('status_payment', models.BooleanField(default=True, verbose_name='Pagada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
