# Generated by Django 2.2.1 on 2023-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Tamaños recomendados: Desde 100x100 hasta 500x500 pixeles', upload_to='', verbose_name='Imagen')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del autor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Testimonio')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
