# Generated by Django 2.2.1 on 2023-03-12 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de la orden')),
                ('status', models.BooleanField(default=True, verbose_name='Estado de pago')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
