# Generated by Django 2.2.1 on 2023-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('image', models.FileField(blank=True, help_text='Tamaños recomendados: Desde 100x100 hasta 500x500 pixeles', upload_to='', verbose_name='Imagen del producto')),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
